### PR TITLE
Abstraction of CalendarRequest to ResourceRequest and parsing moved t…

### PR DESCRIPTION
**Pull request by naramski**
Hi ! 
I've performed a smallest, more easy to review change request. This only move the parsing of CalDAV resources to CalendarResourceParser and generalize the HTTP method handler. 
I hope you'll find this more easy to review than the previous pull request, and hopefully help me also for the maintenance of the carddav part. 
Kind regards, 
David

### CODE REVIEW

**Comment by TheAntimist** [comment]
@naramski Looks like this got lost in the noise, I only found out about this right now. I think the main concern is probably versioning of CalDAV4j, as 1.0.0 might then contain too many API changes. I will need to create a separate branch for CardDAV and let's work on it there until completion?

**Comment by ioggstream** [comment]
@TheAntimist if the APIs are changed, we should create a new branch.

**Comment by ioggstream** [comment]
I created the `devel` branch. We can redirect the PR there!

**Comment by ioggstream** [comment]
@TheAntimist I directed this PR to `devel` branch. Should we merge?

**Comment by TheAntimist** [comment]
Sounds good to me. Go ahead please.

**Comment by naramski** [comment]
Thanks, it will help me to maintain the addon in a separate repository.

**Pull request merged**
