### PR TITLE
Remove redundant spaces.

### PR DESCRIPTION
**Pull request by alejo-enix**

### CODE REVIEW

**Comment by ioggstream** [comment]
close and reopen for CI

**Comment by ioggstream** [comment]
@alejo-enix thanks for this PR! I think that this issue should be addressed integrating a linter into the project. Can you please make a linter proposal and add eventually add a maven target to the pom?

Thanks for all your contribution! It is very appreciate!

**Comment by alejo-enix** [comment]
Sure, I'll be working on it this next week-end.
Should I close the PR then?

**Comment by ioggstream** [comment]
Try to reuse this PR, thanks:)

**Comment by ioggstream** [comment]
As per #126 this PR should be implemented via google-java-format.

**Pull request closed without merging**
