### PR TITLE
fixes null pointer exception when property value is null

### PR DESCRIPTION
**Pull request by teymourlouie**
CalendarDataProperty class could not handle properties with null value. e.g.
<calendar-data xmlns="urn:ietf:params:xml:ns:caldav"/>

### CODE REVIEW

**Comment by teymourlouie** [comment]
@ioggstream I just added some unit tests.

Best,
Mehdi

**Comment by TheAntimist** [comment]
@ioggstream @teymourlouie The changes look fine, unfortunately merge based on PR #89 , there's a merge conflict. I can fix the conflict later this week.

If you want you could rebase on Master and then make the change, which should be the same.

**Comment by teymourlouie** [comment]
@ioggstream @TheAntimist I rebased the branch with master and also squashed two commits into one. also I fixed a bug in my tests. Now it seems cleaner.

**Comment by TheAntimist** [comment]
Looks good, will merge soon.

**Pull request merged**
